<?php
return [
    'html_lang' => 'en',
    'title' => 'le ciel — AI Image Generator',
    'lead' => 'your sky, your creation',
    'hero_cta' => 'Generate Images',
    'hero_cta_login' => 'Sign In',
    'scroll' => 'scroll',

    // Story 1
    'story1_catch' => 'The quiet joy of imagining',
    'story1_body' => 'Turn the landscapes in your mind into reality.<br>le ciel is an AI image generation tool that embraces your imagination.',

    // Story 2
    'story2_catch' => 'Why le ciel?',
    'story2_specs' => [
        'Pay-as-you-go based on actual GPU cost — no hidden markup',
        'No setup required — generate instantly from your browser',
        'Apply any LoRA from the web via URL',
        'Use your own LoRA published on Civitai or GitHub',
        'Switch between multiple AI models with one click',
        'Full control over Steps, CFG, Seed and other parameters',
        'The ideal testbed for new models',
    ],

    // Story 3
    'story3_catch' => 'Paint your own sky',
    'cta' => 'Begin Creating',
    'cta_sub' => 'Google account required / 18+',

    // How it Works
    'how_title' => 'How it Works',
    'step1_title' => 'Choose a Model',
    'step1_desc' => 'Pick the best AI model and LoRA for your purpose',
    'step2_title' => 'Describe Your Vision',
    'step2_desc' => 'Convey your ideal image with prompts and parameters',
    'step3_title' => 'Generate',
    'step3_desc' => 'High-quality images generated in seconds',

    // Gallery
    'gallery_title' => 'Generated by le ciel',
    'gallery_captions' => [
        'Anime / Forest scene / LoRA applied',
        'Anime / Kimono portrait / Custom model',
        'Anime / Fantasy portrait / Fine-tuned',
        'Anime / Night cityscape / Hi-res',
        'Anime / Ocean sunset / Stylized',
        'Anime / Mountain vista / Detailed',
    ],

    // FAQ
    'faq_title' => 'FAQ',
    'faq' => [
        [
            'q' => 'How does pricing work?',
            'a' => 'We use a prepaid system. Purchase USD credits via Stripe, which are consumed based on actual GPU cost per generation. Image storage incurs a separate monthly fee.',
        ],
        [
            'q' => 'What do I need to sign up?',
            'a' => 'A Google account is required. You must be 18 or older to use the service.',
        ],
        [
            'q' => 'Who owns the generated images?',
            'a' => 'Rights to generated images belong to the user, subject to the license terms of the AI model used. See our <a href="service.php" style="color:var(--accent)">Terms of Service</a> for details.',
        ],
        [
            'q' => 'Which models are supported?',
            'a' => 'We support multiple models including Stable Diffusion, with fine-grained style control through LoRA combinations. The service operates as a generative AI model testing platform.',
        ],
    ],

    // Final CTA
    'final_catch' => 'Imagination, realized',

    // Footer
    'terms' => 'Terms of Service',
];
