<?php
return [
    'html_lang' => 'ja',
    'title' => 'le ciel — AI 画像生成',
    'lead' => 'your sky, your creation',
    'hero_cta' => '画像を生成する',
    'hero_cta_login' => 'Sign In',
    'scroll' => 'scroll',

    // Story 1
    'story1_catch' => '想像するという静かな喜び',
    'story1_body' => '頭の中にある風景を、そのまま形にする。<br>le ciel は、あなたの想像力に寄り添う AI 画像生成ツールです。',

    // Story 2
    'story2_catch' => 'Why le ciel?',
    'story2_specs' => [
        'GPU 実費ベースの従量課金 — 余計なマージンなし',
        '環境構築不要 — ブラウザだけで即生成',
        'Web 上の LoRA を URL 指定で自由に適用',
        '自作 LoRA も Civitai や GitHub で公開すれば利用可能',
        '複数の AI モデルをワンクリックで切替',
        'Steps, CFG, Seed など主要パラメータを完全制御',
        '新モデルの検証環境として最適',
    ],

    // Story 3
    'story3_catch' => 'あなたの空を、描こう',
    'cta' => 'Begin Creating',
    'cta_sub' => 'Google アカウントが必要です / 18歳以上',

    // How it Works
    'how_title' => 'How it Works',
    'step1_title' => 'Choose a Model',
    'step1_desc' => '目的に合わせて最適なAIモデルとLoRAを選ぶ',
    'step2_title' => 'Describe Your Vision',
    'step2_desc' => 'プロンプトとパラメータで理想のイメージを伝える',
    'step3_title' => 'Generate',
    'step3_desc' => '数秒で高品質な画像が生成される',

    // Gallery
    'gallery_title' => 'Generated by le ciel',
    'gallery_captions' => [
        'Anime / Forest scene / LoRA applied',
        'Anime / Kimono portrait / Custom model',
        'Anime / Fantasy portrait / Fine-tuned',
        'Anime / Night cityscape / Hi-res',
        'Anime / Ocean sunset / Stylized',
        'Anime / Mountain vista / Detailed',
    ],

    // FAQ
    'faq_title' => 'FAQ',
    'faq' => [
        [
            'q' => '料金体系は？',
            'a' => 'プリペイド制です。Stripe 経由で USD クレジットを購入し、生成ごとに実際の GPU コストに基づいて消費されます。画像の保存には別途月額ストレージ料がかかります。',
        ],
        [
            'q' => 'アカウント登録に必要なものは？',
            'a' => 'Google アカウントが必要です。18歳以上の方がご利用いただけます。',
        ],
        [
            'q' => '生成した画像の権利は？',
            'a' => '生成画像の権利はユーザーに帰属しますが、使用した AI モデルのライセンス条件に従います。詳細は<a href="service.php" style="color:var(--accent)">利用規約</a>をご確認ください。',
        ],
        [
            'q' => 'どのようなモデルに対応していますか？',
            'a' => 'Stable Diffusion をはじめ複数のモデルに対応しており、LoRA を組み合わせた細かなスタイル調整も可能です。本サービスは生成 AI モデルのテストプラットフォームとして運営されています。',
        ],
    ],

    // Final CTA
    'final_catch' => '想像を、現実に',

    // Footer
    'terms' => '利用規約',
];
